config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :tasks
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :status, presence: true, length: {maximum: 15}
    validates :content, presence: true, length: {maximum: 255}
    
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  before_save {self.email.downcase!}
  
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255}, 
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                    uniqueness: {case_sensitive: false}
    
  has_secure_password
  
  has_many :tasks
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
	
	def require_user_logged_in
		unless logged_in?
			redirect_to login_url
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました'
      redirect_to root_url
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @tasks = current_user.tasks.order(id: :desc).page(params[:page]).per(10)
  end
  
  def show
  end
  
  def new
    @task = current_user.tasks.build
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = "タスクが正常に作成されました"
      redirect_to tasks_url
    else
      flash.now[:danger] = "タスクが作成できませんでした"
      render :new
    end
  end
  
  def edit
  end
  
  def update
    
    if @task.update(task_params)
      flash[:success] = "タスクが正常に更新されました"
      redirect_to tasks_url
    else
      flash.now[:danger] = "タスクが更新できませんでした"
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    flash[:success] = "タスクが正常に削除されました"
    redirect_to tasks_url
  end
  
  
  private

  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end

end
  
  
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザーを登録しました'
      redirect_to root_path
    else
      flash[:danger] = 'ユーザーの登録に失敗しました'
      render :new
    end
  end

  def show
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "/layouts/flash_message" %>
    
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>

  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :status, "ステータス" %>
  <%= f.text_field :status %>

  <%= f.label :content, "タスク" %>
  <%= f.text_field :content %>
  
  <%= f.submit "作成" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスクの編集ページ</h1>

<%= render "form", task: @task %>

<%= link_to "一覧へ戻る", tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.id, task_path(task) %> : <%= task.user.name %> => <%= task.status %>, <%= task.content%></li>
  <% end %>
</ul>

<%= paginate @tasks %>

<%= link_to "タスクの新規作成", new_task_path %>
<%= link_to 'ログアウト', logout_path, method: :delete %>

app/views/tasks/new.html.erb
<h1>新規作成</h1>

<%= render "form", task: @task %>

<%= link_to "一覧へ戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1>タスク詳細ページ</h1>

<div><%= @task.content %></div>

<%= link_to "一覧へ戻る", tasks_path %>
<%= link_to "タスクの編集", edit_task_path(@task) %>
<%= link_to "タスクの削除", task_path(@task), method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= form_with(model: @user, local: true) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name, '名前' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, 'パスワード（確認用）' %>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <%= f.submit '登録' %>
<% end %>